# Generated by Django 3.0 on 2020-01-13 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='student_leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(blank=True, max_length=30, null=True)),
                ('leave_day', models.CharField(blank=True, max_length=10, null=True)),
                ('leave_on', models.CharField(blank=True, max_length=20, null=True)),
                ('leave_session', models.CharField(blank=True, max_length=20, null=True)),
                ('leave_reason', models.CharField(blank=True, max_length=40, null=True)),
                ('leave_discription', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
