# Generated by Django 3.0 on 2020-01-13 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculties', '0002_student_leave'),
    ]

    operations = [
        migrations.DeleteModel(
            name='student_leave',
        ),
    ]
